---
- hosts: Proxmox
  tasks:
    - name: Validar que no exista '{{ vname }}'
      proxmox_kvm:
        api_user: root@pam
        api_password: RpcYoHi6Kb9y
        api_host: '{{ proxmox_server }}'
        name: '{{ vname }}'
        node: '{{ proxmox_node }}'
        state: current
      register: result
      ignore_errors: True
              
    - name: Clonar del source hacia '{{ vname }}'
      proxmox_kvm:
        api_user    : root@pam
        api_password: RpcYoHi6Kb9y
        api_host    : '{{ proxmox_server }}'
        clone       : '{{ source }}'   # The VM source
        name        : '{{ vname }}'
        node        : '{{ proxmox_node }}'
        storage     : local
        format      : qcow2
        timeout     : 500  # Note: The task can take a while. Adapt
        
    - name: Arrancar la maquina virtual recien creada '{{ vname }}'
      proxmox_kvm:
         api_user: root@pam
         api_password: RpcYoHi6Kb9y
         api_host: '{{ proxmox_server }}'
         name: '{{ vname }}'
         node: '{{ proxmox_node }}'
         state      : started
