---
- hosts: servidores_python
  
  tasks:
  - name: Register server to Red Hat.
    redhat_subscription:
      state: present
      username: victor.salgado@opti.com.mx
      password: Dickt0r2021.
      autosubscribe: true
