---
- hosts: servidores_python
  
  tasks:
  - name: Register server to Red Hat.
    redhat_subscription:
      state: present
      username: {{ username }}
      password: {{ password }}
      autosubscribe: true
