---
- hosts: servidores_python
  
  tasks:
    - name: install insights-client
      yum:
        name: insights-client
        state: present
    - name: Register to the Red Hat Access Insights Service
      command: redhat-access-insights --register
