- hosts: Linux
  become: yes

  tasks:
    - name: Install epel-repo
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        state: present
    - name: Install zabbix-repo
      yum:
        name: https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm
        state: present
    - name: Install zabbix-agent
      yum:
        name: zabbix-agent
        state: present
    - name: change zabbix_agentd.conf Server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        state: present
        regexp: 'Server=127.0.0.1'
        line: "Server={{ zabbix_server }}"
    - name: change zabbix_agentd.conf ServerActive
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        state: present
        regexp: 'ServerActive=127.0.0.1'
        line: "ServerActive={{ zabbix_serveractive }}"
    - name: Abrir puerto Agente
      firewalld:
        port: "{{ zabbix_port }}"
        permanent: yes
        state: enabled
    - name: Start zabbix-agent
      service:
        name: zabbix-agent
        state: started
        enabled: yes