---
- hosts: servidores_python
  become: yes

  tasks:
    - name: Install epel-repo
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        state: present
        disable_gpg_check: yes
    - name: install yum-utils
      yum:
        name: yum-utils
        state: present
    - name: Habilitar repo CodeReady
      command: yum-config-manager --enable codeready-builder-for-rhel-8-x86_64-rpms     
    - name: Install fusioninventory-agent
      yum:
        name: fusioninventory-agent
        state: present
    - name: Install fusioninventory-agent-task-inventory
      yum:
        name: fusioninventory-agent-task-inventory
        state: present
    - name: change agent.cfg server
      lineinfile:
        path: "{{ fusioninventory_conf_dir }}/agent.cfg"
        state: present
        regexp: '#server = http://server.domain.com/glpi/plugins/fusioninventory/'
        line: "server ={{ fusioninventory_server }}"        
    - name: Start fusioninventory-agent
      service:
        name: fusioninventory-agent
        state: started
        enabled: yes
