- hosts: ad
	  become: yes
	  
	  tasks:
	    - name: Validar que el usuario exista con la información completa
	      community.windows.win_domain_user:
	        name: "{{ nombre_usuario }}"
	        firstname: "{{ nombre }}"
	        surname: "{{ apellido }}"
	        password: "{{ contraseña }}"
	        state: present
	        groups:
	          - towerUsers
	        street: "{{ calle }}"
	        city: "{{ ciudad }}"
	        state_province: "{{ estado }}"
	        postal_code: "{{ cp }}"
	        country: "{{ pais }}"
	        attributes:
	          telephoneNumber: "{{ telefono }}"
	

	   - name: validar que el usuario este creado y usar las credenciales para crear el usuario
	     community.windows.win_domain_user:
	       name: "{{ nombre_usuario }}"
	       firstname: "{{ nombre }}"
	       surname: "{{ apellido }}"
	       password: "{{ contraseña }}"
	       state: present
	       domain_username: "{{ usuario_admin }}"
	       domain_password: "{{ contraseña_admin }}"
	       domain_server: "{{ servidor_dominio }}"
	

	   - name: validar que el usuario este presente en la OU CN=grafanaUsers,OU=orgGroups,DC=OPTI,DC=CORP
	     community.windows.win_domain_user:
	       name: "{{ nombre_usuario }}"
	       password: "{{ contraseña }}"
	       state: present
	       path: "{{ group_user_distinguishedName }}"
	       groups:
	         - towerUsers
