- hosts: ad
  become: yes
  
  tasks:
    - name: Ensure user bob is present with address information
      community.windows.win_domain_user:
        name: "{{ nombre_usuario }}"
        firstname: "{{ nombre }}"
        surname: "{{ apellido }}"
        password: "{{ contrase単a }}"
        state: present
        groups:
          - Domain Admins
        street: "{{ calle }}"
        city: "{{ ciudad }}"
        state_province: "{{ estado }}"
        postal_code: "{{ cp }}"
        country: "{{ pais }}"
        attributes:
          telephoneNumber: "{{ telefono }}"

  - name: Ensure user bob is created and use custom credentials to create the user
    community.windows.win_domain_user:
      name: "{{ nombre_usuario }}"
      firstname: "{{ nombre }}"
      surname: "{{ apellido }}"
      password: "{{ contrase単a }}"
      state: present
      domain_username: "{{ usuario_admin }}"
      domain_password: "{{ contrase単a_admin }}"
      domain_server: "{{ servidor_dominio }}"

  - name: Ensure user bob is present in OU ou=test,dc=domain,dc=local
    community.windows.win_domain_user:
      name: "{{ nombre_usuario }}"
      password: "{{ contrase単a }}"
      state: present
      path: "{{ group_user_distinguishedName }}"
      groups:
      - towerUsers

  
