- hosts: ad
  become: yes

  tasks:
    - name: Validar que el usuario exista con la información completa 
        community.windows.win_domain_user
          name: "{{ nombreusuario }}"
          firstname: "{{ nombre }}"
          surname: "{{ apellido }}"
          password: "{{ contraseña }}"
          state: present
          groups:
            - towerUsers
          street: "{{ calle }}"
          city: "{{ ciudad }}"
          state_province: "{{ estado }}"
          postal_code: "{{ cp }}"
          country: "{{ pais }}"
          attributes:
            telephoneNumber: "{{ telefono }}"