---
- hosts: lab-oss
  become: yes
  tasks:
    - name: Add an Ethernet connection with static IP configuration
      community.general.nmcli:
        conn_name: my-eth1
        ifname: ens18
        type: ethernet
        ip4: "{{ ip }}"
        gw4: "{{ gateway }}"
        dns4: "{{ dns }}"
        state: present
        autoconnect: yes
      
