---
- hosts: lab-oss
  become: yes
  tasks:
    - name: install needed network manager libs
      package:
        name:
          - NetworkManager-libnm
          - nm-connection-editor
          - python3-libsemanage
          - python3-policycoreutils
        state: present
    - name: Add an Ethernet connection with static IP configuration
      nmcli:
        conn_name: my-eth1
        ifname: ens18
        type: ethernet
        ip4: "{{ ip }}"
        gw4: "{{ gateway }}"
        dns4: "{{ dns }}"
        state: present
        autoconnect: yes
      
